config/routes.rb
Rails.application.routes.draw do
  
  get 'visitors/index'

  get 'visitors/show'

  resources :visitors, only:[:index, :show]
  
  resources :users do 
  	collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/matricappdatum.rb
require 'csv'
class Matricappdatum < ApplicationRecord
	validates :centre_no, :school_name, presence: true, uniqueness: true

	def self.import(file)
		CSV.foreach(file.path) do | row |
			emis, centre_no, sname, wrote_2014, passed_2014, wrote_2015, passed_2015, wrote_2016, passed_2016,
			 pass_rate, failure_rate, pass_rate2015, failure_rate2015, pass_rate2016, failure_rate2016 = row

			Matricappdatum.create(emis: emis, centre_no: centre_no, school_name: sname,
			wrote_2014: wrote_2014, passed_2014: passed_2014, wrote_2015: wrote_2015,
			passed_2015: passed_2015, wrote_2016: wrote_2016, passed_2016: passed_2016,
			pass_rate: pass_rate,failure_rate: failure_rate, pass_rate2015: pass_rate2015, 
			failure_rate2015: failure_rate2015, pass_rate2016: pass_rate2016, failure_rate2016: failure_rate2016)
		end
	end
	def self.search(search)
  		if search
    		where(['centre_no ILIKE? OR school_name ILIKE?', "%#{search}%","%#{search}%"])
  		else
    		all
  		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    def import 
      Matricappdatum.import(params[:file])
      redirect_to users_path, notice: "Report added"
    rescue
      redirect_to users_path, notice: "Report not added"
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  	@matrics = Matricappdatum.all
  end

  def show
  	@matric = Matricappdatum.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matricapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="bs-example">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Matric report</a>
        </div>
        <div id="navbarCollapse" class="collapse navbar-collapse">
       
          <%= form_tag users_path, method: 'get',class: "navbar-form navbar-left" do %>
          <%= text_field_tag :search, params[:search], class: "form-control" %>

          <%= submit_tag "Search" ,class: "btn btn-default"%>
  
        <% end %>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Login</a></li>
            </ul>
        </div>
    </nav>
  </div>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row col-md-12"><div class="col-md-4"> 
  <%= form_tag import_users_path, multipart: true, class: "form-inline" do %>
  <span class="btn btn-xs">
 <%= file_field_tag :file %></span>
 <%= submit_tag "Upload report" ,class: "btn btn-xs btn-outline-success"%>
 <% end %></div>
  <p class="col-md-4"> <%= link_to 'Create New User', new_user_path ,class: "btn btn-outline-success" %></p>
<p class="col-md-4"> <%= link_to 'Add School', new_user_path ,class: "btn btn-outline-success" %></p</div>
 
<h1>Users</h1>

<table class = "table">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class = "table-striped">
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        </td><td><%= link_to 'View', user %></td>
         <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/visitors/index.html.erb
<table class = "table">
  <thead class="thead-dark">
    <tr>
      <th>Emis</th>
      <th>Centre no</th>
      <th>School name</th>
      <th>Wrote 2014</th>
      <th>Passed 2014</th>
      <th>Wrote 2015</th>
      <th>Passed 2015</th>
      <th>Wrote 2016</th>
      <th>Passed 2016</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matrics.each do |report| %>
      <tr class = "table-striped">
        <td><%= report.emis %></td>
        <td><%= report.centre_no %></td>
        <td><%= report.school_name %></td>
        <td><%= report.wrote_2014 %></td>
        <td><%= report.passed_2014 %></td>
        <td><%= report.wrote_2015 %></td>
        <td><%= report.passed_2015 %></td>
        <td><%= report.wrote_2016 %></td>
        <td><%= report.passed_2016 %></td>
        <td><%= link_to 'Show', visitor_url(report) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visitors/show.html.erb
<html>
  <head>
 
<script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Pass Rate', 'Failure rate'],
          ['2014', <%= @matric.pass_rate %>, <%= @matric.failure_rate %>],
          ['2015', <%= @matric.pass_rate2015 %>, <%= @matric.failure_rate2015 %>],
          ['2016', <%= @matric.pass_rate2016 %>, <%= @matric.failure_rate2016 %>]
         
        ]);

        var options = {

          chart: {
            bg: '000000',
            title: '<%= @matric.school_name %>',
            subtitle: 'Report analyser',
            align: "center"
          },
           vAxis: {
          title: 'Percentage (%)',
          minValue: 0,
          maxValue: 100,
          format:'#,##%'
        },
        hAxis: {
          title: 'Year'
        },

          bars: 'vertical' // Required for Material Bar Charts.
        };

        var chart = new google.charts.Bar(document.getElementById('chartcontainer'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
      }
    </script>
       <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Year', 'Number'],
          ['2014',   <%= @matric.wrote_2014%>],
          ['2014',      <%= @matric.passed_2014%>],
          ['2015',  <%= @matric.wrote_2015%>],
          ['2015', <%= @matric.passed_2015%>],
          ['2016', <%= @matric.wrote_2016%>],
          ['2016',    <%= @matric.passed_2016%>]
        ]);

        var options = {
          title: 'My Daily Activities'
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart-container'));

        chart.draw(data, options);
      }
    </script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'pass average'],
          ['2014',  <%= @matric.pass_rate %>],
          ['2015',  <%= @matric.pass_rate2015 %>],
          ['2016',  <%= @matric.pass_rate2016 %>]
        ]);

        var options = {
          title: 'Company Performance',
          curveType: 'function',
          legend: { position: 'bottom' }
        };

        var chart = new google.visualization.LineChart(document.getElementById('barchart_material'));

        chart.draw(data, options);
      }
    </script>
  </head>
  </head>
  <body><div class="container">
<button class="btn btn-premary btn-lg col-md-4 col-xs-4" id="btn1">Bar</button>
<button class="btn btn-premary btn-lg col-md-4 col-xs-4 col-xs-4" id="btn2">Pie</button>
<button class="btn btn-premary btn-lg col-md-4 col-xs-4 col-xs-4" id="btn3">Average</button>
</div>

<div class="container">
<div>
<div id="chartcontainer" style="width: 100%; height: 500px;"></div> 
</div>

<div id="chart-container" style="width: 100%; height: 1000px;"></div> 

<div>
<div id="barchart_material" style="width: 100%; height: 1000px;"></div> 
</div>
</div>

 <script> 
(function ($) {
$('#btn1').click(function () {
$('#chart-container').hide();
$('#barchart_material').hide();
 $('#chartcontainer').slideDown(3000);
  
 }); 
 })(jQuery);
 
 (function ($) {
$('#btn2').click(function () {
$('#chartcontainer').hide(); 
$('#barchart_material').hide();
 $('#chart-container').slideDown(3000); 
  });
 })(jQuery);
 
  (function ($) {
$('#btn3').click(function () {
$('#chartcontainer').hide(); 
$('#chart-container').hide(); 
 $('#barchart_material').slideDown(3000); 
  });
 })(jQuery);
 </script>
  </body>
</html>